---
- name: Set Timestamp
  set_fact:
    time: "{{lookup('pipe','date \"+%Y-%m-%d-%H-%M\"')}}"
  run_once: true

- name: Create default tag
  ansible.builtin.set_fact:
    default_tag:
      annotation: "{{ time }}"
      message: "backup_on: {{ time }}"

- name: Set default tag
  ansible.builtin.set_fact:
    default_tag: "{}"
  when:
    - data_store.scm.origin.tag  is defined 
    - "{{ data_store.scm.origin.tag }}  == 'default'"

- name: Publish the changes
  ansible.scm.git_publish:
    path: "{{ network_backup_path }}"
    token: "{{ data_store['scm']['origin']['token'] | d(None) }}"
    user: "{{ data_store['scm']['origin']['user'] | d({}) }}"
    tag: "{{ data_store.scm.origin.tag | d(default_tag) }}"
    timeout: 120
