---
- name: Perform retrieve with provided credentials
  when: data_store.scm.origin.token is defined
  block:
    - name: Retrieve the host vars with provided token access
      ansible.scm.git_retrieve:
        origin:
          url: "{{ data_store['scm']['origin']['url'] }}"
          token: "{{ data_store['scm']['origin']['token'] }}"
          tag: "{{ data_store.scm.origin.tag | default(None)}}"
        parent_directory: "{{ data_store.scm.parent_directory | default('./') }}"
      register: resource_manager_result

    - name: Update data store path
      ansible.builtin.set_fact:
        network_backup_repository: "{{ resource_manager_result }}"

- name: Perform retrieve with default settings
  when: data_store.scm.origin.token is undefined
  block:
    - name: Retrieve host vars with default access
      ansible.scm.git_retrieve:
        origin:
          url: "{{ data_store['scm']['origin']['url'] }}"
          tag: "{{ data_store.scm.origin.tag | default(None)}}"
        parent_directory: "{{ data_store.scm.parent_directory | default('./') }}"
      register: resource_manager_result

    - name: Update data store path
      ansible.builtin.set_fact:
        network_backup_repository: "{{ resource_manager_result }}"

- name: Update Inventory Path
  ansible.builtin.set_fact:
    network_backup_path: "{{ network_backup_repository['path'] }}"
